#pragma once

#include <cstdint>
#include <string>
#include <string_view>

#include "autonomous_foundry/export.hpp"

// Version metadata for the Autonomous Foundry runtime.
//
// The values here are generated by CMake from the single project(... VERSION)
// declaration so that the compiled version, the installed package version and
// the source tree can never disagree.

// The build system supplies these from the single project(... VERSION)
// declaration. The fallbacks below only exist so that the public headers can be
// parsed standalone (an editor, a compile probe, a documentation generator); a
// real build always defines them, and the installed package version is written
// from the same declaration, so the two can never drift.
#ifndef AUTONOMOUS_FOUNDRY_VERSION_MAJOR
#  define AUTONOMOUS_FOUNDRY_VERSION_MAJOR 1
#endif
#ifndef AUTONOMOUS_FOUNDRY_VERSION_MINOR
#  define AUTONOMOUS_FOUNDRY_VERSION_MINOR 0
#endif
#ifndef AUTONOMOUS_FOUNDRY_VERSION_PATCH
#  define AUTONOMOUS_FOUNDRY_VERSION_PATCH 0
#endif
#ifndef AUTONOMOUS_FOUNDRY_VERSION_STRING
#  define AUTONOMOUS_FOUNDRY_VERSION_STRING "1.0.0"
#endif

namespace autonomous_foundry {

inline constexpr std::uint32_t kVersionMajor = AUTONOMOUS_FOUNDRY_VERSION_MAJOR;
inline constexpr std::uint32_t kVersionMinor = AUTONOMOUS_FOUNDRY_VERSION_MINOR;
inline constexpr std::uint32_t kVersionPatch = AUTONOMOUS_FOUNDRY_VERSION_PATCH;

/// Semantic version string, for example "1.0.0".
[[nodiscard]] AUTONOMOUS_FOUNDRY_API std::string_view version_string() noexcept;

/// Numeric version packed as (major << 16) | (minor << 8) | patch.
[[nodiscard]] AUTONOMOUS_FOUNDRY_API std::uint32_t version_number() noexcept;

/// Human readable build description: name, version, compiler and platform.
[[nodiscard]] AUTONOMOUS_FOUNDRY_API std::string build_description();

/// Durable snapshot format version understood by this build.
inline constexpr std::uint32_t kSnapshotFormatVersion = 1;

/// Wire protocol version understood by this build.
inline constexpr std::uint16_t kProtocolVersion = 1;

}  // namespace autonomous_foundry
